services:
  forms-backend:
    container_name: forms-backend
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=True
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  forms-frontend:
    container_name: forms-frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"
    depends_on:
      - forms-backend

